@startuml
'Attribute syntax: <visibility> <name> : <type> <multiplicity> = <default>
'Method syntax: <visibility> <name (parameter-list)> : <return-type> - For simplicity the type of the parameter-list is not specified

class UserProjectDTO {
    +projectCode : String
    +projectName : String

    +equals(object : Object) : boolean
    +hashCode() : int
}

@enduml