@startuml

title US032 - As a Team Member, I want to add a user story in the product backlog to the sprint backlog, during the sprint planning ceremony in the web UI

package "src" {
    package "routes" {
    }

    package "pages" {
    }

    package "components" {

        package "sprintBacklog" {
        }

    }

    package "context" {
    }
    package "services" {
        }
}

src ..> components
src ..> routes
routes ..> pages
pages ..> components
pages ..> sprintBacklog
sprintBacklog ..> context
pages ..> context
context ..> services


@enduml
