@startuml

skinparam UsecaseBackgroundColor white
skinparam ActorBackgroundColor white

left to right direction

actor "Administrator" as A
actor "Manager" as M
actor "Product Owner" as PO
actor "Scrum Master" as SM
actor "Team Member" as TM
actor "Project Manager" as PM

rectangle System {
    usecase "US010: register/create a new project" as UC10
    usecase "US011: associate a user as Team Member of a project" as UC11
    usecase "US012: define the Product Owner of a project" as UC12
    usecase "US013: define the Scrum Master of a project" as UC13
    usecase "US015: get a list of all projects" as UC15
    usecase "US017: create a user story and add\n it to the product backlog" as UC17
    usecase "US018: consult the product backlog" as UC18
    usecase "US019: create a sprint" as UC19
    usecase "US023: As an Administrator, I want to create a Project in the web UI." as UC23
    usecase "US024: As an Administrator, I want list all Project in the web UI." as UC24
    usecase "US025: As a Product Owner, I want to create a user story and add it to the Product Backlog using the web UI." as UC25
    usecase "US026: As a PO/SM/Team Member, I want to consult the current Product Backlog in the web UI." as UC26
    usecase "US027: As a Project Manager, I want to create a sprint in the web UI." as UC27
    usecase "US028: As Manager, I want to associate a user as Team Member of a project in the web UI." as UC28
    usecase "US029: As Manager, I want to define the PO of a project in the web UI." as UC29
    usecase "US030: As Manager, I want to define the SM of a project in the web UI." as UC30
}

M --> UC10
M --> UC11
M --> UC12
M --> UC13
M --> UC15
M --> UC17
M --> UC18
M --> UC19
A --> UC23
A --> UC24
PO --> UC25
PO --> UC26
SM --> UC26
TM --> UC26
PM --> UC27
M --> UC28
M --> UC29
M --> UC30

@enduml