@startuml

skinparam sequenceMessageAlign center
skinparam actorBackgroundColor white
skinparam participantBackgroundColor white
skinparam sequenceReferenceBackgroundColor white
skinparam sequenceReferenceHeaderBackgroundColor white
skinparam sequenceGroupBackgroundColor white

autonumber
title US006 - As Administrator, I want to activate a user account

actor ":Administrator" as Administrator #white
participant ":ActivateAccountUI" as UI #white
participant ":ActivateAccount\nController" as Controller #white
participant "accountService\n:AccountService" as Service
participant "<<DomainID>>\nemail : Email" as Email
participant "<<Repository>>\n:AccountRepository" as AccountRepository
participant "<<ValueObject>>\naccountStatus\n:AccountStatus" as Status
participant "account\n:Account" as account #white


Administrator -> UI++: asks to activate account

    UI -> Controller++: activateAccount(emailValue)
            Controller -> Service++: changeAccountStatus(emailValue, accountStatusValue)

                create Email
                        Service -> Email : create(emailValue)

                Service -> AccountRepository++: findByID(email)
                return accountOptional

                    create Status
                           Service -> Status : create(accountStatusValue)


                Service -> account++: setAccountStatus(accountStatus)
                   return true/false






            return true/false
    return true/false
return successful/unsuccessful

@enduml