@startuml

skinparam sequenceMessageAlign center
autonumber

title US014 - As Manager, I want to get a list of all human resources in a project

actor ":Manager" as Manager #white
participant ":System" as System #white

Manager -> System : requests list of all human resources in a project
System --> Manager: returns list of all human resources in a project

@enduml