@startmindmap

title US031 -  As Project Manager, I want to start the next sprint of a project in the web UI
top to bottom direction

* <&globe>Application
** Navbar
*** NavItem
** MainRoute
*** Projects
**** ProjectPage
***** ProjectPageTable\n(Project Info)
***** Button\n(Back)
***** Button\n(Product Backlog)
***** Button \n(Sprints)
****** Sprint Page
******* Button\n(Create Sprint)
******* Button\n(All Sprints)
******* Button\n(Open next Sprint)
******* Button\n(Back)
***** Button\n(Resources)
***** Button\n(Status History)


@endmindmap