@startuml

skinparam sequenceMessageAlign center
autonumber

actor "Project Manager" as PM
participant ":System" as System

PM -> System: associates activity to project
System --> PM: shows confirmation

@enduml
