@startuml

'left to right direction

title Implementation View - Level 3

package Backend {
    package controller #white{
    }

    package service #white{
    }

    package repository #white{
    }

    package datamodel #white{
    }

    package domain #white{
    }

    package utils #white{
    }
}

controller ..> service
controller ..> utils

service ..> utils
service ..> repository
service ..> domain

repository ..> datamodel
repository ..> domain

datamodel ..> domain

@enduml