@startuml
 'https://plantuml.com/use-case-diagram

skinparam sequenceMessageAlign center
autonumber

actor User
participant ":System" as System

User -> System: logs time record on task
System --> User: shows confirmation

@enduml
