@startuml
 'https://plantuml.com/use-case-diagram

skinparam sequenceMessageAlign center
autonumber

actor User
participant ":System" as System

User -> System: updates task
System --> User: shows confirmation of update

@enduml
