@startuml

skinparam sequenceMessageAlign center
autonumber

actor "Team Member"
participant ":System" as System

"Team Member" -> System: registers work in task
System --> "Team Member": confirms registrations of work in task

@enduml