@startuml

class ChangeProfileController{
    -accountService : AccountService {readOnly}

    +ChangeProfileController(accountService : AccountService)
    +changeProfileOfAccount(userEmail : String, desiredProfile : String)
}

@enduml