@startuml

class CreateProjectTypologyController {
- projectTypologyService : ProjectTypologyService

+ CreateProjectTypologyController(projectTypologyService : ProjectTypologyService)
+ createProjectTypology(name : String) : boolean

}

@enduml