@startuml

class CreateBusinessSectorController {
    - businessSectorService : BusinessSectorService {readOnly}

    + CreateBusinessSectorController(businessSectorService : BusinessSectorService)
    + createBusinessSector(businessSectorNameValue : String) : boolean
}

@enduml