@startuml
'https://plantuml.com/class-diagram

class CustomerValueObjectDTO {
    + taxIdentificationNumber : TaxIdentificationNumber
    + customerName : CustomerName
    + country : Country

    + equals(o : Object) : boolean
    + hashCode() : int
}

@enduml