@startuml
'Attribute syntax: <visibility> <name> : <type> <multiplicity> = <default>
'Method syntax: <visibility> <name (parameter-list)> : <return-type> - For simplicity the type of the parameter-list is not specified

class Description<<Value Object>> {
    - descriptionValue : String {readOnly}

    + Description(descriptionValue : String)
    - validateValue(descriptionValue : String) {static}
    + getDescriptionValue() : String
    + equals(o : Object) : boolean
    + hashCode() : int
}



@enduml