@startuml
'https://plantuml.com/class-diagram

class OutputCustomerDTO {
    + taxIdentificationNumber : String
    + customerName : String
    + country : String

    + equals(o : Object) : boolean
    + hashCode() : int
}

@enduml