@startuml
'Attribute syntax: <visibility> <name> : <type> <multiplicity> = <default>
'Method syntax: <visibility> <name (parameter-list)> : <return-type> - For simplicity the type of the parameter-list is not specified

class PhoneNumber<<ValueObject>> {
    -phoneNumber : int

    +PhoneNumber(phoneNumber : int)
    -isValid(phoneNumber : int) : boolean
    -countPhoneNumberDigits(phoneNumber : int) : int
    +toInteger() : int
    +equals(object : Object) : boolean
    +hashCode() : int
}

@enduml