@startuml
'https://plantuml.com/class-diagram

class ProfileRepositoryPersistence<<Repository>> {
    '- profileRepositoryJPA : ProfileRepositoryJPA {readOnly}
    '- profileDomainDataAssembler : ProfileDomainDataAssembler {readOnly}

    + save(profile : Profile) : UserStory
    + findAll(profileName : ProfileName) : Iterable
    + findById(profileName : ProfileName) : Optional
    + existsById(profileName : ProfileName) : boolean
    + deleteAll()
    + deleteById(profileName : profileName)
}

@enduml