@startuml
'Attribute syntax: <visibility> <name> : <type> <multiplicity> = <default>
'Method syntax: <visibility> <name (parameter-list)> : <return-type> - For simplicity the type of the parameter-list is not specified

class ProfileController<<Controller>> {
    '- profileService : ProfileService {readOnly}

    + ProfileController(profileService : ProfileService)
    + createProfile(newProfileDTO : NewProfileDTO) : ResponseEntity
    + getProfile(profileName : String) : ResponseEntity
}

@enduml