@startuml

class ProjectDomainDataAssembler {
    - projectFactory : ProjectFactory {readOnly}

    + ProjectDomainDataAssembler(projectFactory : ProjectFactory)
    + toData(project : Project) : ProjectJPA
    + toDomain(projectJPA : ProjectJPA) : Project
}

@enduml