@startuml

interface ResourceFactory<<Factory>>{

    + createResource(resourceID : ResourceID, roleInProject : ProjectRole,
     percentageOfAllocation : PercentageOfAllocation, costPerHour : CostPerHour) : Resource
}

@enduml