@startuml
'Attribute syntax: <visibility> <name> : <type> <multiplicity> = <default>
'Method syntax: <visibility> <name (parameter-list)> : <return-type> - For simplicity the type of the parameter-list is not specified

class ResourceJPA {
    - resourceIDJpa: ResourceIdJPA
    - projectRole: String
    - percentageOfAllocation: Integer
    - costPerHour: Double

    +ResourceJPA(resourceIDJpa: ResourceIdJPA, projectRole: String, percentageOfAllocation: Integer, costPerHour:
    Double)
    #ResourceJPA()
    +getResourceIDJpa(): ResourceIdJPA
    +getProjectRole(): String
    +getPercentageOfAllocation(): Integer
    +getCostPerHour(): Double
    +equals(o: Object): boolean
    +hashCode(): int
}

@enduml