@startuml

class SprintBacklogJPA {

    - sprintIdJPA : SprintIdJPA
    - userStoryCodeList : String

    # SprintBacklogJPA()
    + SprintBacklogJPA(sprintIdJPA : SprintIdJPA, userStoryCodeList : String)
    + getSprintIdJPA() : SprintIdJPA
    + getUserStoryCodeList() : String
    + equals(o : Object) : boolean
    + hashCode() : int
}

@enduml