@startuml
'https://plantuml.com/class-diagram

class UserStoryRepositoryPersistence<<Repository>> {
    - jpaRepository : UserStoryRepositoryJPA
    - jpaAssembler : UserStoryDomainDataAssembler

    + UserStoryRepositoryPersistence(jpaRepository : UserStoryRepositoryJPA, jpaAssembler : UserStoryDomainDataAssembler)
    + save(domainUserStory : UserStory) : UserStory
    + findAll() : Iterable<UserStory>
    + findByID(id : UserStoryID) : Optional<UserStory>
    + existsByID(id : UserStoryID) : boolean
    + findByProjectCodeAndUserStoryStatusNotAndUserStoryStatusNot(projectCode : ProjectCode,\n firstStatus : UserStoryStatus, secondStatus : UserStoryStatus) : Iterable<UserStory>
    + deleteAll()
    + deleteById(id : UserStoryID)
    + findAllByID(listOfIDs : Iterable<UserStoryID>) : Iterable<UserStory>
    + patch(patchedUserStory : UserStory) : UserStory
    + existsByUserStoryIdAndUserStoryStatusNotAndUserStoryStatusNot\n(userStoryID : UserStoryID, fisrtStatus : UserStoryStatus, secondStatus \n: UserStoryStatus) : boolean

}

@enduml