@startuml
'Attribute syntax: <visibility> <name> : <type> <multiplicity> = <default>
'Method syntax: <visibility> <name (parameter-list)> : <return-type> - For simplicity the type of the parameter-list is not specified

class UserStoryController<<Controller>> {
    - userStoryService : UserStoryService {readOnly}

    + UserStoryController(userStoryService : UserStoryService)
    + createUserStory(newUserStoryDTO : NewUserStoryDTO) : ResponseEntity<Object>
    + updateUserStoryStatus(projectCode : ProjectCode, userStoryCode : UserStoryCode, inputUserStoryStatus : UserStoryStatus) : ResponseEntity<Object>
}

@enduml