@startuml

skinparam sequenceMessageAlign center
autonumber

actor Admin
participant ":System" as System

Admin -> System: Associates user account into existing account
System --> Admin: Confirms association


@enduml